/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import DAO.TaskDAO;
import DAO.MemberDAO;
import Model.Task;
import Model.Member;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class ManageTask extends javax.swing.JFrame {
    private TaskDAO taskDAO = new TaskDAO();
    private MemberDAO memberDAO = new MemberDAO();

    /**
     * Creates new form ManageTask
     */
    public ManageTask() {
        initComponents();
        setLocationRelativeTo(null);
        txtTaskID.setEditable(false);        // ID comes from DB, not user

        loadMembersIntoCombo();             // fill AssignedTo from Members table
        txtDescription.setLineWrap(true);
        txtDescription.setWrapStyleWord(true);
    }
    
    private void loadMembersIntoCombo() {
    try {
        jcbAssignedTo.removeAllItems();
        List<Member> members = memberDAO.getAllMembers();
        for (Member m : members) {
            jcbAssignedTo.addItem(m.getMemberID() + " - " + m.getName());
        }
        jcbAssignedTo.setSelectedIndex(-1);  // nothing selected initially
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this,
                "Error loading members:\n" + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
    }
}

// Parse "123 - Name" → 123
private Integer getSelectedMemberIdFromCombo() {
    Object item = jcbAssignedTo.getSelectedItem();
    if (item == null) {
        return null;
    }
    try {
        String text = item.toString();
        String idStr = text.split("-")[0].trim();
        return Integer.parseInt(idStr);
    } catch (Exception e) {
        return null;
    }
}

// Read taskID from txtTaskID
private Integer getTaskIdFromField() {
    String text = txtTaskID.getText().trim();
    if (text.isEmpty()) return null;
    try {
        return Integer.parseInt(text);
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this,
                "Task ID must be an integer.",
                "Validation", JOptionPane.WARNING_MESSAGE);
        return null;
    }
}

// Clear inputs
private void clearTaskFields() {
    txtTaskID.setText("");
    txtTitle.setText("");
    txtDescription.setText("");
    txtDueDate.setText("");
    jcbAssignedTo.setSelectedIndex(-1);
    jcbStatus.setSelectedIndex(0);   // first status item
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTaskID = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        lblAssignedTo = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblDueDate = new javax.swing.JLabel();
        txtTaskID = new javax.swing.JTextField();
        txtTitle = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        txtDueDate = new javax.swing.JTextField();
        jbAddTask = new javax.swing.JToggleButton();
        jbDeleteTask = new javax.swing.JToggleButton();
        jbUpdateTask = new javax.swing.JToggleButton();
        jbClearTask = new javax.swing.JToggleButton();
        jbViewAllTask = new javax.swing.JToggleButton();
        jbBack = new javax.swing.JToggleButton();
        jcbAssignedTo = new javax.swing.JComboBox<>();
        jcbStatus = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTaskID.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblTaskID.setText("TaskID :");

        lblTitle.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblTitle.setText("Title :");

        lblDescription.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblDescription.setText("Description :");

        lblAssignedTo.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblAssignedTo.setText("Assigned To :");

        lblStatus.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblStatus.setText("Status :");

        lblDueDate.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblDueDate.setText("Due Date :");

        txtTaskID.setEditable(false);
        txtTaskID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTaskIDActionPerformed(evt);
            }
        });

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane1.setViewportView(txtDescription);

        jbAddTask.setText("Add Task");
        jbAddTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddTaskActionPerformed(evt);
            }
        });

        jbDeleteTask.setText("Delete Task");
        jbDeleteTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeleteTaskActionPerformed(evt);
            }
        });

        jbUpdateTask.setText("Update Task");
        jbUpdateTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUpdateTaskActionPerformed(evt);
            }
        });

        jbClearTask.setText("Clear Task");
        jbClearTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbClearTaskActionPerformed(evt);
            }
        });

        jbViewAllTask.setText("View All Task");
        jbViewAllTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbViewAllTaskActionPerformed(evt);
            }
        });

        jbBack.setText("Back");
        jbBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBackActionPerformed(evt);
            }
        });

        jcbAssignedTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jcbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PENDING", "IN-PROGRESS", "DONE", "ASSIGNED" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lblAssignedTo)
                            .addGap(6, 6, 6))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lblDueDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescription)
                            .addComponent(lblTitle)
                            .addComponent(lblTaskID, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtTitle)
                        .addComponent(txtTaskID)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtDueDate)
                        .addComponent(jcbStatus, 0, 281, Short.MAX_VALUE)
                        .addComponent(jcbAssignedTo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jbAddTask, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbViewAllTask)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbBack, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbDeleteTask)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbUpdateTask)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbClearTask, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTaskID)
                    .addComponent(txtTaskID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescription)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAssignedTo)
                    .addComponent(jcbAssignedTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDueDate)
                    .addComponent(txtDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAddTask)
                    .addComponent(jbDeleteTask)
                    .addComponent(jbUpdateTask)
                    .addComponent(jbClearTask))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbViewAllTask)
                    .addComponent(jbBack))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbUpdateTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUpdateTaskActionPerformed
    Integer taskID = getTaskIdFromField();
    if (taskID == null) {
        JOptionPane.showMessageDialog(this,
                "Select a task to update (TaskID must be filled).",
                "Validation", JOptionPane.WARNING_MESSAGE);
        return;
    }

    String title  = txtTitle.getText().trim();
    String desc   = txtDescription.getText().trim();
    String status = jcbStatus.getSelectedItem().toString();
    String dueStr = txtDueDate.getText().trim();
    Integer memberID = getSelectedMemberIdFromCombo();

    if (title.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Title is required.",
                "Validation", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        Task t = new Task();
        t.setTaskID(taskID);
        t.setTitle(title);
        t.setDescription(desc);
        t.setStatus(status);

        if (memberID != null) {
            Member m = new Member();
            m.setMemberID(memberID);
            t.setAssignedTo(m);
        }

        if (!dueStr.isEmpty()) {
            java.sql.Date sqlDate = java.sql.Date.valueOf(dueStr);
            t.setDueDate(new java.util.Date(sqlDate.getTime()));
        }

        taskDAO.updateTask(t);
        JOptionPane.showMessageDialog(this, "Task updated.");

        clearTaskFields();
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this,
                "Error updating task:\n" + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jbUpdateTaskActionPerformed

    private void jbViewAllTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbViewAllTaskActionPerformed
    ViewAllTask view = new ViewAllTask();
    view.setLocationRelativeTo(this);
    view.setVisible(true);
    }//GEN-LAST:event_jbViewAllTaskActionPerformed

    private void jbBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBackActionPerformed
        AdminDashboard admin = new AdminDashboard();
        admin.setLocationRelativeTo(null);
        admin.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jbBackActionPerformed

    private void txtTaskIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTaskIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTaskIDActionPerformed

    private void jbAddTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddTaskActionPerformed
    String title  = txtTitle.getText().trim();
    String desc   = txtDescription.getText().trim();
    String status = jcbStatus.getSelectedItem().toString();
    String dueStr = txtDueDate.getText().trim();
    Integer memberID = getSelectedMemberIdFromCombo();

    if (title.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Title is required.",
                "Validation", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        Task t = new Task();
        t.setTitle(title);
        t.setDescription(desc);
        t.setStatus(status);

        if (memberID != null) {
            Member m = new Member();
            m.setMemberID(memberID);
            t.setAssignedTo(m);
        }

        if (!dueStr.isEmpty()) {
            // expects yyyy-MM-dd
            java.sql.Date sqlDate = java.sql.Date.valueOf(dueStr);
            t.setDueDate(new java.util.Date(sqlDate.getTime()));
        }

        taskDAO.addTask(t);
        JOptionPane.showMessageDialog(this, "Task added successfully.");

        clearTaskFields();
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this,
                "Error adding task:\n" + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jbAddTaskActionPerformed

    private void jbDeleteTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeleteTaskActionPerformed
     Integer taskID = getTaskIdFromField();
    if (taskID == null) {
        JOptionPane.showMessageDialog(this,
                "Select a task to delete (TaskID must be filled).",
                "Validation", JOptionPane.WARNING_MESSAGE);
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete this task?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION);

    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    try {
        taskDAO.deleteTask(taskID);
        JOptionPane.showMessageDialog(this, "Task deleted.");

        clearTaskFields();
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this,
                "Error deleting task:\n" + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jbDeleteTaskActionPerformed

    private void jbClearTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbClearTaskActionPerformed
    clearTaskFields();
    }//GEN-LAST:event_jbClearTaskActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageTask().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jbAddTask;
    private javax.swing.JToggleButton jbBack;
    private javax.swing.JToggleButton jbClearTask;
    private javax.swing.JToggleButton jbDeleteTask;
    private javax.swing.JToggleButton jbUpdateTask;
    private javax.swing.JToggleButton jbViewAllTask;
    private javax.swing.JComboBox<String> jcbAssignedTo;
    private javax.swing.JComboBox<String> jcbStatus;
    private javax.swing.JLabel lblAssignedTo;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblDueDate;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTaskID;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtDueDate;
    private javax.swing.JTextField txtTaskID;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
